config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  scope '', as: 'home' do
    root 'home#index'
    post '/lead_opportunity', to: 'home#lead_opportunity', as: 'lead_opportunity'
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    scope 'jobs', as: 'jobs' do
      get '', to: 'jobs#index'
      get '/new', to: 'jobs#new'

      post '', to: 'jobs#create', as: 'create'
    end
  end

  namespace :sessions do
    scope 'signup', as: 'signup' do
      get '', to: 'signup#signup'
      post '', to: 'signup#create', as: 'create'
    end

    scope 'signin' do
      get '', to: 'signin#signin', as: 'signin'
      post '', to: 'signin#authenticate', as: 'authenticate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_save { self.email = email.downcase }

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authorized?
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index; end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  def initialize
    @cron_service = Cron::Service.new
    @dto = Cron::Dto.new
    super
  end

  def index
    response = @cron_service.list(@current_user.id)
    @jobs = response.present? ? response.map { |job| @dto.from_response(job) } : []
  end

  def new; end

  def create
    request = @dto.to_request(job_params.merge(user_id: @current_user.id))
    @cron_service.create(request)

    redirect_to admin_jobs_url
  end

  private

  def job_params
    params.permit(:name, :expression, :webhook_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authorized?
    redirect_to sessions_sigin_url, status: :unauthorized unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def lead_opportunity
    email = lead_params[:email]
    redirect_to sessions_signup_path and return if email.blank?

    user_exists = User.find_by(email: email)

    if user_exists.present?
      redirect_to sessions_signin_path(email: email) and return
    else
      redirect_to sessions_signup_path(email: email) and return
    end
  end

  private

  def lead_params
    params.permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_svg(path)
    File.open("app/assets/images/#{path}", 'rb') do |file|
      raw file.read
    end
  end

  def last_run_in_words(date)
    "Last run at #{date.to_datetime.strftime('%B %e, %Y %H:%M')}"
  end

  def next_run_in_words(date)
    now = DateTime.now.strftime('%a, %d %b %Y %H:%M:%S').to_datetime
    future_date = date.to_datetime
    return 'Should not run again' if future_date < now

    "Next run in #{distance_of_time_in_words(now, future_date)}"
  end

  def cron_expression_in_words(expression)
    Cronex::ExpressionDescriptor.new(expression).description
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/dashboard/_graph.html.erb
<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">
  <div class="flex items-center justify-between mb-4">
    <div class="flex-shrink-0">
      <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">$45,385</span>
      <h3 class="text-base font-normal text-gray-500">Sales this month</h3>
    </div>
    <div class="flex items-center justify-end flex-1 text-green-500 text-base font-bold">
      12.5%
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
      </svg>
    </div>
  </div>
  <div id="main-chart"></div>
</div>

app/views/admin/dashboard/_latest_runs.html.erb
<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 ">
  <div class="mb-4 flex items-center justify-between">
    <div>
      <h3 class="text-xl font-bold text-gray-900 mb-2">Latest Runs</h3>
      <span class="text-base font-normal text-gray-500">This is a list of latest runs</span>
    </div>
    <div class="flex-shrink-0">
      <a href="#" class="text-sm font-medium text-cyan-600 hover:bg-gray-100 rounded-lg p-2">View all</a>
    </div>
  </div>
  <div class="flex flex-col mt-8">
    <div class="overflow-x-auto rounded-lg">
      <div class="align-middle inline-block min-w-full">
        <div class="shadow overflow-hidden sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Task 
                </th>
                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Date & Time
                </th>
                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Status 
                </th>
              </tr>
            </thead>
            <tbody class="bg-white">
              <tr>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                  Payment from <span class="font-semibold">Bonnie Green</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 23 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-red-600">
                  Failed 
                </td>
              </tr>
              <tr class="bg-gray-50">
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 rounded-lg rounded-left">
                  Payment refund to <span class="font-semibold">#00910</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 23 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-green-600">
                  Success 
                </td>
              </tr>
              <tr>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                  Payment failed from <span class="font-semibold">#087651</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 18 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-green-600">
                  Success 
                </td>
              </tr>
              <tr class="bg-gray-50">
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 rounded-lg rounded-left">
                  Payment from <span class="font-semibold">Lana Byrd</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 15 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-red-600">
                  Failed 
                </td>
              </tr>
              <tr>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                  Payment from <span class="font-semibold">Jese Leos</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 15 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-green-600">
                  Success
                </td>
              </tr>
              <tr class="bg-gray-50">
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 rounded-lg rounded-left">
                  Payment from <span class="font-semibold">THEMESBERG LLC</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 11 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-green-600">
                  Success
                </td>
              </tr>
              <tr>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                  Payment from <span class="font-semibold">Lana Lysle</span>
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                  Apr 6 ,2021
                </td>
                <td class="p-4 whitespace-nowrap text-sm font-semibold text-green-600">
                  Success
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="w-full grid grid-cols-1 xl:grid-cols-2 2xl:grid-cols-3 gap-4">
  <%= render "graph" %> 
  <%= render "latest_runs" %> 
</div>
<div class="mt-4 w-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 mb-6">
  <div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 ">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">2,340</span>
        <h3 class="text-base font-normal text-gray-500">Tasks ran this month</h3>
      </div>
      <div class="ml-5 w-0 flex items-center justify-end flex-1 text-green-500 text-base font-bold">
        14.6%
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
      </div>
    </div>
  </div>
  <div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 ">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">5,355</span>
        <h3 class="text-base font-normal text-gray-500">Tasks succeeded this month</h3>
      </div>
      <div class="ml-5 w-0 flex items-center justify-end flex-1 text-green-500 text-base font-bold">
        32.9%
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
      </div>
    </div>
  </div>
  <div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">385</span>
        <h3 class="text-base font-normal text-gray-500">User signups this week</h3>
      </div>
      <div class="ml-5 w-0 flex items-center justify-end flex-1 text-red-500 text-base font-bold">
        -2.7%
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M14.707 12.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 14.586V3a1 1 0 012 0v11.586l2.293-2.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
        </svg>
      </div>
    </div>
  </div>
</div>

app/views/admin/jobs/_form.html.erb
<%= form_with url: admin_jobs_create_path , method: :post, class: "divide-y divide-gray-200 mt-6" do |form| %>
  <div class="divide-y divide-gray-200">
    <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
      <div class="flex flex-col">
        <label class="leading-loose">Task Name</label>
        <%= form.text_field :name, class:"px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600", placeholder:"Event title" %>
      </div>
      <div class="flex flex-col">
        <label class="leading-loose">Cron Expression</label>
        <%= form.text_field :expression, class:"px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600", placeholder:"30 2 * 2 1-5" %>
      </div> 
      <div class="flex flex-col">
        <label class="leading-loose">Webhook URL</label>
        <%= form.text_field :webhook_url, class:"px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600", placeholder:"https://myapi.com/webhook"%>
      </div>
    </div>
    <div class="pt-4 flex items-center space-x-4"> 
      <%= form.submit "Create", class:"bg-cyan-600 hover:bg-cyan-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none" %>
    </div>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="sm:px-6 w-full">
  <div class="px-4 md:px-10 py-4 md:py-7">
    <div class="flex items-center justify-between">
      <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800">Tasks</p>
      <div class="py-3 px-4 flex items-center text-sm font-medium leading-none text-gray-600 cursor-pointer rounded">
        <p>Sort By:</p>
        <select aria-label="select" class="focus:text-indigo-600 focus:outline-none bg-transparent ml-1">
          <option class="text-sm text-indigo-800">Latest</option>
          <option class="text-sm text-indigo-800">Oldest</option>
        </select>
      </div>
    </div>
  </div>
  <div class="bg-white py-4 md:py-7 px-4 md:px-8 xl:px-10 mb-16" style="min-height: 36rem">
    <div class="sm:flex items-center justify-end">
      <%= link_to admin_jobs_new_path, class:"focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 mt-4 sm:mt-0 inline-flex items-start justify-start px-6 py-3 bg-cyan-600 hover:bg-cyan-500 focus:outline-none rounded" do %>
        <p class="text-sm font-medium leading-none text-white">Add Task</p>
      <% end %>
    </div>
    <div class="mt-7 overflow-x-auto">
      <%= render "table" %>
    </div>
  </div>
</div>

app/views/admin/jobs/new.html.erb
<div class="py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">
            <%= show_svg('clock.svg') %>
          </div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <h2 class="leading-relaxed">Create a Task</h2>
            <p class="text-sm text-gray-500 font-normal leading-relaxed">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
          </div>
        </div>
          <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_lead_form.html.erb
<%= form_with url: home_lead_opportunity_url, method: :post, class:"flex flex-col md:flex-row" do |form| %>
  <%= form.email_field :email, placeholder:"Enter your email address", class:"m-1 h-10 flex-1 appearance-none border-none bg-transparent px-4 py-2 text-gray-700 placeholder-gray-400 focus:placeholder-transparent focus:outline-none focus:ring-0 dark:text-gray-200" %>

  <%= form.submit "Start Now", class:"cursor-pointer m-1 h-10 transform rounded-md bg-cyan-600 px-4 py-2 text-white transition-colors duration-300 hover:bg-cyan-500 focus:bg-blue-400 focus:outline-none" %>
<% end %>

app/views/home/_nav.html.erb
<nav x-data="{ isOpen: false }" class="container mx-auto p-6 lg:flex lg:items-center lg:justify-between">
  <div class="flex items-center justify-between">
    <div>
      <a class="text-2xl font-bold text-gray-800 hover:text-gray-700 dark:text-white dark:hover:text-gray-300 lg:text-3xl" href="#">Chronos</a>
    </div>

    <!-- Mobile menu button -->
    <div class="flex lg:hidden">
      <button x-cloak @click="isOpen = !isOpen" type="button" class="text-gray-500 hover:text-gray-600 focus:text-gray-600 focus:outline-none dark:text-gray-200 dark:hover:text-gray-400 dark:focus:text-gray-400" aria-label="toggle menu">
        <svg x-show="!isOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M4 8h16M4 16h16" />
        </svg>

        <svg x-show="isOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
  <div x-cloak :class="[isOpen ? 'translate-x-0 opacity-100 ' : 'opacity-0 -translate-x-full']" class="absolute inset-x-0 z-20 w-full bg-white px-6 py-4 shadow-md transition-all duration-300 ease-in-out dark:bg-gray-900 lg:relative lg:top-0 lg:mt-0 lg:flex lg:w-auto lg:translate-x-0 lg:items-center lg:bg-transparent lg:p-0 lg:opacity-100 lg:shadow-none lg:dark:bg-transparent">
    <div class="flex flex-col space-y-4 lg:mt-0 lg:flex-row lg:space-y-0">
      <a class="text-gray-700 hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-400 lg:mx-6" href="#">Home</a>
      <a class="text-gray-700 hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-400 lg:mx-6" href="#">Pricing</a>
      <a class="text-gray-700 hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-400 lg:mx-6" href="#">Contact</a>
      <a class="text-gray-700 hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-400 lg:mx-6" href="#">FAQ</a>
    </div>

    <%= link_to "Sign In", sessions_signin_url, class:"mt-4 block h-10 transform rounded-md border px-5 py-2 text-center text-sm capitalize text-gray-700 transition-colors duration-300 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 lg:mt-0 lg:w-auto" %>
  </div>
</nav>

app/views/layouts/_side_menu.html.erb
<aside id="sidebar" class="fixed hidden z-20 h-full top-0 left-0 pt-16 flex lg:flex flex-shrink-0 flex-col w-64 transition-width duration-75" aria-label="Sidebar">
  <div class="relative flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white pt-0">
    <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
      <div class="flex-1 px-3 bg-white divide-y space-y-1">
        <ul class="space-y-2 pb-2"> 
          <li>
            <%= link_to admin_dashboard_path , class:"text-base text-gray-900 font-normal rounded-lg flex items-center p-2 hover:bg-gray-100 group" do %>
              <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900 transition duration-75" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
                <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
              </svg>
              <span class="ml-3">Dashboard</span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_jobs_path, class:"text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group" do %>
              <%= show_svg('clock_solid.svg') %> 
              <span class="ml-3 flex-1 whitespace-nowrap">Tasks</span>
            <% end %>
          </li>
          <li>
            <a href="#" target="_blank" class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group ">
              <svg class="w-6 h-6 text-gray-500 flex-shrink-0 group-hover:text-gray-900 transition duration-75" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path>
              </svg>
              <span class="ml-3 flex-1 whitespace-nowrap">Integrations</span>
              <span class="bg-gray-200 text-gray-800 ml-3 text-sm font-medium inline-flex items-center justify-center px-2 rounded-full">Pro</span>
            </a>
          </li> 
          <li>
            <a href="#" class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group ">
              <%= show_svg('settings.svg') %>
              <span class="ml-3 flex-1 whitespace-nowrap">Settings</span>
            </a>
          </li>
        </ul>
        <div class="space-y-2 pt-2">
          <a href="#" class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 group transition duration-75 flex items-center p-2">
            <svg class="w-5 h-5 text-gray-500 flex-shrink-0 group-hover:text-gray-900 transition duration-75" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="gem" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
              <path fill="currentColor" d="M378.7 32H133.3L256 182.7L378.7 32zM512 192l-107.4-141.3L289.6 192H512zM107.4 50.67L0 192h222.4L107.4 50.67zM244.3 474.9C247.3 478.2 251.6 480 256 480s8.653-1.828 11.67-5.062L510.6 224H1.365L244.3 474.9z"></path>
            </svg>
            <span class="ml-4">Upgrade to Pro</span>
          </a>
          <a href="#" target="_blank" class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 group transition duration-75 flex items-center p-2">
            <svg class="w-6 h-6 text-gray-500 flex-shrink-0 group-hover:text-gray-900 transition duration-75" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
              <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd"></path>
            </svg>
            <span class="ml-3">Documentation</span>
          </a>
          <a href="#" target="_blank" class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 group transition duration-75 flex items-center p-2">
            <svg class="w-6 h-6 text-gray-500 flex-shrink-0 group-hover:text-gray-900 transition duration-75" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-2 0c0 .993-.241 1.929-.668 2.754l-1.524-1.525a3.997 3.997 0 00.078-2.183l1.562-1.562C15.802 8.249 16 9.1 16 10zm-5.165 3.913l1.58 1.58A5.98 5.98 0 0110 16a5.976 5.976 0 01-2.516-.552l1.562-1.562a4.006 4.006 0 001.789.027zm-4.677-2.796a4.002 4.002 0 01-.041-2.08l-.08.08-1.53-1.533A5.98 5.98 0 004 10c0 .954.223 1.856.619 2.657l1.54-1.54zm1.088-6.45A5.974 5.974 0 0110 4c.954 0 1.856.223 2.657.619l-1.54 1.54a4.002 4.002 0 00-2.346.033L7.246 4.668zM12 10a2 2 0 11-4 0 2 2 0 014 0z" clip-rule="evenodd"></path>
            </svg>
            <span class="ml-3">Help</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CronWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main> 
      <%= yield %>
    </main>
  </body>
</html>